### ISSUE TITLE
LSD Save File Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPG-Maker-Specifications#1]
Complete the specification for LSD save files.

- [x] Create a document and mark as _Researching_.
- [x] Preliminary research and outline.
- [ ] Complete research and begin finalization.
- [ ] Finish finalizing and mark specification as complete.
