### ISSUE TITLE
RPG Maker 2003 Runtime Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPG-Maker-Specifications#11]
Complete the specification for the RPG Maker 2003 (RM2k3) runtime. Parenthesis indicate a relevant folder found in an RM2k3 game directory.

- [ ] Create a document.

__Note:__ The following items are in no particular order.

- [ ] Input.
  - [ ] Keyboard and mouse.
  - [ ] Special inputs (e.g. F4).
- [ ] Graphics and rendering.
  - [ ] Rendering in general.
    - [ ] Limitations and supported image formats.
    - [ ] Animation.
    - [ ] Screen effects.
  - [ ] Backdrops. (Backdrop)
  - [ ] Characters and monsters. (CharSet, FaceSet, Monster)
  - [ ] Tilesets. (ChipSet)
  - [ ] System images. (System, System2)
  - [ ] Battle images. (Battle, BattleCharSet, BattleWeapon)
  - [ ] Panoramas. (Panorama)
  - [ ] "Title" images. (Title, GameOver)
  - [ ] General images. (Picture)
- [ ] Audio.
  - [ ] Audio in general.
    - [ ] Limitations and supported audio formats.
  - [ ] Music (Music).
  - [ ] Sound effects (Sound).
- [ ] Dialog system.
  - [ ] Dialog boxes.
  - [ ] Fonts (ultimate_rt_eb).
  - [ ] Handling text: "localization" and encoding.
- [ ] Scripting and events.
- [ ] Battle system.
- [ ] Debugging.
- [ ] Runtime packages (RTP).
- [ ] Runtime resources (ultimate_rt_eb).
- [ ] Additional considerations.
  - [ ] Solutions to common problems.
  - [ ] [EasyRPG Player](https://github.com/EasyRPG/Player)
