### ISSUE TITLE
RPG Maker 2003 Editor Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPG-Maker-Specifications#12]
Complete the specification for the RPG Maker 2003 editor.

- [ ] Create a document.

__Note:__ The following items are not in a strict order and are non-exhaustive.

- [ ] Preliminary.
  - [ ] Brief history.
  - [ ] Editor implementation details.
    - [ ] Supported platforms.
  - [ ] Configuration. (RPG_RT.ini)
- [ ] Overview of UI.
- [ ] Project management.
  - [ ] Project directory structure.
- [ ] Map editing.
- [ ] Tools.
  - [ ] Database
  - [ ] Resource manager.
  - [ ] Event search.
- [ ] Debugging/testing.
- [ ] Distribution/gamedisk.
