### ISSUE TITLE
LMU Map File Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPG-Maker-Specifications#3]
Complete the specification for LMU map files.

- [ ] Create a document and mark as _Researching_.
- [ ] Preliminary research and outline.
- [ ] Complete research and begin finalization.
- [ ] Finish finalizing and mark specification as complete.
