### ISSUE TITLE
Rewrite specs in LaTeX

### ISSUE THREAD

**Issue by napen123** [chika-games/RPG-Maker-Specifications#9]
To allow for more portability (Markdown, PDF, HTML, etc.) and layout control, rewrite all of the existing specs in LaTeX.

- [X] XYZ
- [X] Config (RPG_RT.ini)
- [ ] LCF Map Tree (LMT)
- [ ] Delete Markdown versions.
